"""Add admin role and update Post model

Revision ID: 08cb31736205
Revises: c3dee948351d
Create Date: 2025-08-13 10:30:05.574049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08cb31736205'
down_revision = 'c3dee948351d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_binary', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('days_left',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.alter_column('days_left',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('priority',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('image_binary')

    # ### end Alembic commands ###
